channels:
- conda-forge
dependencies:
- python=3.11.8
- pip<=23.3.2
- pip:
  - mlflow==2.3
  - cffi==1.16.0
  - cloudpickle==2.2.1
  - graphviz==0.20.1
  - importlib-metadata==6.11.0
  - jinja2==3.1.3
  - matplotlib==3.7.5
  - numpy==1.24.4
  - packaging==23.2
  - pandas==2.1.4
  - pyarrow==11.0.0
  - pycaret==3.3.2
  - scikit-learn==1.4.2
  - scipy==1.11.4
name: mlflow-env
