apiVersion: apps/v1
kind: Deployment
metadata:
  name: training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
      - name: training
        image: gcr.io/docker-mlops-pipeline/training:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_PATH
          value: /app/db/
        volumeMounts:
        - name: db-volume
          mountPath: /app/db
      volumes:
      - name: db-volume
        emptyDir: {}
